import * as IconList from "@/public/assets/icons";

export type IconName =
  | "about-fill"
  | "activity"
  | "about"
  | "add-fill"
  | "arrow-bottom-left-small"
  | "arrow-bottom-left"
  | "arrow-bottom-right-small"
  | "arrow-bottom-right"
  | "arrow-double-down-small"
  | "arrow-double-left-small"
  | "arrow-double-left"
  | "arrow-double-right-small"
  | "arrow-double-right"
  | "arrow-double-up-small"
  | "arrow-down"
  | "arrow-left-lg"
  | "arrow-left"
  | "arrow-right-lg"
  | "arrow-right"
  | "arrow-top-left-small"
  | "arrow-top-left"
  | "arrow-top-right-small"
  | "arrow-top-right"
  | "arrow-up"
  | "bar-graph-fill"
  | "bar-graph"
  | "bitcoin-fill"
  | "bitcoin"
  | "camera-fill"
  | "camera"
  | "chevron-down-small"
  | "chevron-down"
  | "chevron-left-small"
  | "chevron-left"
  | "chevron-right-small"
  | "chevron-right"
  | "chevron-up-small"
  | "chevron-up"
  | "close-fill"
  | "coin-swap-fill"
  | "coin-swap"
  | "configuration"
  | "copy-fill"
  | "copy"
  | "cross"
  | "day-fill"
  | "download-file"
  | "day"
  | "download"
  | "exclamation-fill"
  | "exclamation"
  | "eye-hide-fill"
  | "eye-hide"
  | "eye-view-fill"
  | "eye-view"
  | "farm"
  | "filter"
  | "gas-fill"
  | "gas"
  | "info-fill"
  | "info"
  | "link"
  | "lock-fill"
  | "lock"
  | "menu-small"
  | "menu"
  | "minus-fill"
  | "minus"
  | "more"
  | "night-fill"
  | "night"
  | "notification-fill"
  | "notification"
  | "pie-chart-fill"
  | "pie-chart"
  | "play-fill"
  | "plus"
  | "redo"
  | "play"
  | "resizer"
  | "search"
  | "send-fill"
  | "send"
  | "settings-fill"
  | "settings"
  | "support-fill"
  | "support"
  | "refresh"
  | "swap-horizontal"
  | "swap-vertical"
  | "switch-off"
  | "tick-fill"
  | "tick"
  | "token-fill"
  | "token"
  | "undo"
  | "unlock-fill"
  | "unlock"
  | "user-fill"
  | "user"
  | "warning-fill"
  | "warning";

export const iconMap: Record<IconName, any> = {
  "about-fill": IconList.AboutFill,
  about: IconList.About,
  activity: IconList.Activity,
  "add-fill": IconList.AddFill,
  "arrow-bottom-left-small": IconList.ArrowBottomLeftSmall,
  "arrow-bottom-left": IconList.ArrowBottomLeft,
  "arrow-bottom-right-small": IconList.ArrowBottomRightSmall,
  "arrow-bottom-right": IconList.ArrowBottomRight,
  "arrow-double-down-small": IconList.ArrowDoubleDownSmall,
  "arrow-double-left-small": IconList.ArrowDoubleLeftSmall,
  "arrow-double-left": IconList.ArrowDoubleLeft,
  "arrow-double-right-small": IconList.ArrowDoubleRightSmall,
  "arrow-double-right": IconList.ArrowDoubleRight,
  "arrow-double-up-small": IconList.ArrowDoubleUpSmall,
  "arrow-down": IconList.ArrowDown,
  "arrow-left-lg": IconList.ArrowLeftLg,
  "arrow-left": IconList.ArrowLeft,
  "arrow-right-lg": IconList.ArrowRightLg,
  "arrow-right": IconList.ArrowRight,
  "arrow-top-left-small": IconList.ArrowTopLeftSmall,
  "arrow-top-left": IconList.ArrowTopLeft,
  "arrow-top-right-small": IconList.ArrowTopRightSmall,
  "arrow-top-right": IconList.ArrowTopRight,
  "arrow-up": IconList.ArrowUp,
  "bar-graph-fill": IconList.BarGraphFill,
  "bar-graph": IconList.BarGraph,
  "bitcoin-fill": IconList.BitcoinFill,
  bitcoin: IconList.Bitcoin,
  "camera-fill": IconList.CameraFill,
  camera: IconList.Camera,
  "chevron-down-small": IconList.ChevronDownSmall,
  "chevron-down": IconList.ChevronDown,
  "chevron-left-small": IconList.ChevronLeftSmall,
  "chevron-left": IconList.ChevronLeft,
  "chevron-right-small": IconList.ChevronRightSmall,
  "chevron-right": IconList.ChevronRight,
  "chevron-up-small": IconList.ChevronUpSmall,
  "close-fill": IconList.CloseFill,
  "coin-swap-fill": IconList.CoinSwapFill,
  "coin-swap": IconList.CoinSwap,
  "chevron-up": IconList.ChevronUp,
  "copy-fill": IconList.CopyFill,
  configuration: IconList.Configuration,
  copy: IconList.Copy,
  "day-fill": IconList.DayFill,
  day: IconList.Day,
  "download-file": IconList.DownloadFile,
  download: IconList.Download,
  "exclamation-fill": IconList.ExclamationFill,
  exclamation: IconList.Exclamation,
  "eye-hide-fill": IconList.EyeHideFill,
  "eye-hide": IconList.EyeHide,
  cross: IconList.Cross,
  "eye-view-fill": IconList.EyeViewFill,
  "eye-view": IconList.EyeView,
  farm: IconList.Farm,
  filter: IconList.Filter,
  "gas-fill": IconList.GasFill,
  "info-fill": IconList.InfoFill,
  gas: IconList.Gas,
  link: IconList.Link,
  lock: IconList.Lock,
  "lock-fill": IconList.LockFill,
  "menu-small": IconList.MenuSmall,
  menu: IconList.Menu,
  "minus-fill": IconList.MinusFill,
  minus: IconList.Minus,
  more: IconList.More,
  info: IconList.Info,
  night: IconList.Night,
  "notification-fill": IconList.NotificationFill,
  notification: IconList.Notification,
  "pie-chart-fill": IconList.PieChartFill,
  "pie-chart": IconList.PieChart,
  "play-fill": IconList.PlayFill,
  "night-fill": IconList.NightFill,
  plus: IconList.Plus,
  redo: IconList.Redo,
  refresh: IconList.Refresh,
  play: IconList.Play,
  resizer: IconList.Resizer,
  search: IconList.Search,
  "send-fill": IconList.SendFill,
  send: IconList.Send,
  "settings-fill": IconList.SettingsFill,
  settings: IconList.Settings,
  "support-fill": IconList.SupportFill,
  support: IconList.Support,
  "swap-vertical": IconList.SwapVertical,
  "swap-horizontal": IconList.SwapHorizontal,
  tick: IconList.Tick,
  "tick-fill": IconList.TickFill,
  "token-fill": IconList.TokenFill,
  "switch-off": IconList.SwitchOff,
  undo: IconList.Undo,
  token: IconList.Token,
  "user-fill": IconList.UserFill,
  user: IconList.User,
  "warning-fill": IconList.WarningFill,
  warning: IconList.Warning,
  "unlock-fill": IconList.UnlockFill,
  unlock: IconList.Unlock,
};

export interface IconProps {
  alt?: string;
  className?: string;
  name: IconName;
  size?: number;
}

export const Icon = ({ alt, className, name, size = 20 }: IconProps) => {
  const IconComponent = iconMap[name];

  return (
    <IconComponent
      className={className}
      height={size}
      title={alt ? alt : name}
      width={size}
    />
  );
};
